Profil
WildCodeSchool/purple-php-2109-project3-skillswap pull request #13
Opened 2022-01-10 10:04 UTC by Bruno-Fernandes-37

2022-01-10 10:19 UTC, Benjamin-51 submitted a review, later dismissed

2022-01-10 11:12 UTC, sebastien-violante submitted a review, later dismissed

2022-01-11 15:16 UTC, RomainClair requested changes

2022-01-11 15:16 UTC, RomainClair commented on src/Controller/UsersController.php
> +            'user' => $user,
Du you really need the user object to be passed to your view ?

2022-01-12 15:20 UTC, Benjamin-51 approved these changes
The change I asked over discord is done, so I approve.

2022-01-13 08:17 UTC, RomainClair approved these changes

2022-01-13 08:18 UTC, merged