No s
WildCodeSchool/purple-php-2109-project3-skillswap pull request #15
Opened 2022-01-11 16:08 UTC by Bruno-Fernandes-37

correction of my error on the entities created in the plural

2022-01-11 16:17 UTC, sebastien-violante approved these changes, later dismissed
No useless 's' anymore ! Congratulation(s) !

2022-01-12 10:45 UTC, Benjamin-51 requested changes
In the skill controller, the parameter $skillsRepository still has an s and should be removed.
Also in the same file, I think it would be better to add the name "skill_" in the route on line 14 and update the subsequent routes.

2022-01-12 11:06 UTC, Bruno-Fernandes-37 commented
about the route we will change if we add methods in the class, knowing that the method show is removed in a next pr. the modification on the variable is done

2022-01-12 11:15 UTC, Benjamin-51 submitted a review, later dismissed

2022-01-13 08:31 UTC, Benjamin-51 approved these changes

2022-01-13 10:05 UTC, RomainClair approved these changes

2022-01-13 10:06 UTC, merged