Admin user
WildCodeSchool/purple-php-2109-project3-skillswap pull request #28
Opened 2022-01-15 18:50 UTC by Bruno-Fernandes-37

possibility for the administrator to view the list of users and the details of each of them

2022-01-17 09:11 UTC, go37 approved these changes
ok

2022-01-17 13:02 UTC, go37 submitted a review, later dismissed
ok

2022-01-17 15:17 UTC, CECDO approved these changes, later dismissed

2022-01-17 15:22 UTC, RomainClair requested changes
public/upload/avatars should be in the .gitignore

2022-01-17 15:45 UTC, sebastien-violante approved these changes

2022-01-17 15:46 UTC, go37 approved these changes

2022-01-17 15:46 UTC, CECDO approved these changes

2022-01-18 09:20 UTC, RomainClair approved these changes

2022-01-18 09:20 UTC, merged