Navbar
WildCodeSchool/purple-php-2109-project3-skillswap pull request #3
Opened 2021-12-15 14:20 UTC by Bruno-Fernandes-37

2021-12-15 14:32 UTC, Benjamin-51 submitted a review, later dismissed
Read and approved.

2021-12-15 16:42 UTC, sebastien-violante approved these changes, later dismissed

2021-12-16 07:54 UTC, RomainClair requested changes
The composer.json seems to not have been restored to the initial (dev) state

2021-12-16 08:57 UTC, sebastien-violante approved these changes, later dismissed

2021-12-16 14:12 UTC, RomainClair approved these changes

2021-12-16 14:42 UTC, Benjamin-51 approved these changes

2021-12-16 15:13 UTC, merged