Swapper display
WildCodeSchool/purple-php-2109-project3-skillswap pull request #35
Opened 2022-01-17 14:42 UTC by sebastien-violante

The aim is to display the card of the selected swapper, containing all references about him.

2022-01-17 15:12 UTC, go37 approved these changes, later dismissed
ok

2022-01-18 10:18 UTC, RomainClair requested changes
You shouldn't upload temporary test datas in the repository (and probably add the upload/avatars to the .gitignore)

2022-01-18 10:43 UTC, go37 approved these changes

2022-01-18 13:09 UTC, RomainClair approved these changes

2022-01-18 13:09 UTC, merged