Us9 1 create swap
WildCodeSchool/purple-php-2109-project3-skillswap pull request #39
Opened 2022-01-18 14:40 UTC by CECDO

creation of the swap form

2022-01-18 15:24 UTC, Bruno-Fernandes-37 requested changes
overriding methods that should not be in swapController, no version file ..... no big deal for sure

2022-01-18 16:11 UTC, go37 submitted a review, later dismissed

2022-01-18 16:42 UTC, Bruno-Fernandes-37 submitted a review, later dismissed

2022-01-21 08:52 UTC, RomainClair requested changes
The fixtures need to be fixed according to the database changes

2022-01-24 08:37 UTC, Benjamin-51 commented
> The fixtures need to be fixed according to the database changes

What fixtures would we need to change? We are unsure about if this current PR requires changes or if we need to update them like adding skills and comments to our users.

2022-01-24 09:55 UTC, Bruno-Fernandes-37 approved these changes, later dismissed
it all looks good for me

2022-01-24 10:31 UTC, Bruno-Fernandes-37 approved these changes

2022-01-24 10:44 UTC, RomainClair approved these changes

2022-01-24 10:44 UTC, RomainClair commented on src/Controller/SwapController.php
> +                $swap->setDate(new DateTime());
This could have been done in the Swap construct

2022-01-24 10:44 UTC, RomainClair commented on src/Entity/Swap.php
> +    private string $message;
You probably should have constraints to validate the message... May be avoiding empty messages ?

2022-01-24 10:44 UTC, merged