Delete user fixtures
WildCodeSchool/purple-php-2109-project3-skillswap pull request #68
Opened 2022-01-27 20:54 UTC by sebastien-violante

2022-01-27 22:38 UTC, Bruno-Fernandes-37 requested changes
the pr fixture will be in conflict

2022-01-28 08:13 UTC, Bruno-Fernandes-37 approved these changes

2022-01-28 08:14 UTC, go37 approved these changes

2022-01-28 08:14 UTC, Benjamin-51 approved these changes

2022-01-28 08:33 UTC, merged