Page 404 personalization
WildCodeSchool/purple-php-2109-project3-skillswap pull request #90
Opened 2022-02-01 15:02 UTC by sebastien-violante

2022-02-01 15:10 UTC, go37 submitted a review, later dismissed

2022-02-02 13:40 UTC, RomainClair requested changes

2022-02-02 13:40 UTC, RomainClair commented on templates/registration/register.html.twig
> +    <div>
This is probably invalid HTML

2022-02-06 13:14 UTC, sebastien-violante commented on templates/registration/register.html.twig
> +    <div>
Effectively...

2022-02-07 09:01 UTC, Bruno-Fernandes-37 approved these changes

2022-02-07 09:11 UTC, CECDO approved these changes

2022-02-07 09:14 UTC, go37 approved these changes

2022-02-07 09:29 UTC, RomainClair approved these changes

2022-02-07 10:32 UTC, go37 approved these changes

2022-02-07 15:06 UTC, Bruno-Fernandes-37 approved these changes

2022-02-07 16:28 UTC, RomainClair approved these changes

2022-02-07 16:28 UTC, merged